// <auto-generated>
// Generated by AudioEventIdGenerator from an AudioDatabase asset.
// DO NOT EDIT MANUALLY. Edit AudioDatabase_Main and regenerate.
// </auto-generated>

public enum AudioEventId
{
    // SFX
    Player_Charge = 17,
    Player_Death = 18,
    Player_Hit = 19,
    Player_MassNugget = 20,
    Player_Parry = 21,
    Player_ShieldBreak = 22,
    Player_ShieldUp = 23,
    Player_Spawn = 24,
    Player_Stunned = 25,
    Player_SwordAttack = 26,

    // UI
    UI_Navigate = 11,
    UI_Confirm = 12,
    UI_Back = 13,
    UI_Error = 14,
    UI_PlayerJoin = 15,
    UI_PlayerReady = 16,

}

