#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

public static class AudioEventIdGenerator
{
    public const string DefaultOutputPath = "Assets/Audio/Scripts/AudioEventId.cs";

    private sealed class Record
    {
        public string group;
        public string name;
        public int value;
        public bool deprecated;
    }

    [MenuItem("Tools/MASSIVE/Audio/Regenerate AudioEventId.cs")]
    public static void RegenerateFromSelection()
    {
        var db = Selection.activeObject as AudioDatabase;
        if (db == null)
        {
            EditorUtility.DisplayDialog(
                "Regenerate AudioEventId.cs",
                "Select an AudioDatabase asset in the Project window (e.g. AudioDatabase_Main), then run this command again.",
                "OK");
            return;
        }

        Generate(db, DefaultOutputPath, showDialogOnSuccess: true);
    }

    public static void Generate(AudioDatabase db, string outputPath, bool showDialogOnSuccess = false)
    {
        if (db == null) throw new ArgumentNullException(nameof(db));

        db.MigrateLegacyEntriesIfNeeded();
        EditorUtility.SetDirty(db);

        var records = BuildRecords(db);
        ValidateRecords(records);

        string contents = BuildEnumFile(records);

        string fullPath = Path.Combine(Directory.GetCurrentDirectory(), outputPath);
        string dir = Path.GetDirectoryName(fullPath);
        if (!Directory.Exists(dir))
            Directory.CreateDirectory(dir);

        File.WriteAllText(fullPath, contents, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

        AssetDatabase.ImportAsset(outputPath, ImportAssetOptions.ForceUpdate);
        AssetDatabase.Refresh();

        Debug.Log($"[AudioEventIdGenerator] Wrote {records.Count} entries to: {outputPath}");

        var script = AssetDatabase.LoadAssetAtPath<MonoScript>(outputPath);
        if (script != null)
        {
            EditorGUIUtility.PingObject(script);
            AssetDatabase.OpenAsset(script);
        }

        if (showDialogOnSuccess)
        {
            EditorUtility.DisplayDialog(
                "Regenerate AudioEventId.cs",
                $"Generated:\n{outputPath}\n\nUnity will recompile scripts now.",
                "OK");
        }
    }

    private static List<Record> BuildRecords(AudioDatabase db)
    {
        var list = new List<Record>(256);

        foreach (var (entry, group) in db.EnumerateAllEntriesWithGroup(includeDeprecated: true))
        {
            if (!entry.assigned) continue;
            if (string.IsNullOrWhiteSpace(entry.name)) continue;

            string clean = SanitizeToIdentifier(entry.name);

            list.Add(new Record
            {
                group = group,
                name = clean,
                value = entry.value,
                deprecated = entry.deprecated
            });
        }

        return list;
    }

    private static void ValidateRecords(List<Record> records)
    {
        var dupName = records.GroupBy(r => r.name).Where(g => g.Count() > 1).Select(g => g.Key).ToList();
        if (dupName.Count > 0)
            throw new Exception("Duplicate AudioEventId names after sanitization:\n- " + string.Join("\n- ", dupName));

        var dupValue = records.GroupBy(r => r.value).Where(g => g.Count() > 1).Select(g => g.Key).ToList();
        if (dupValue.Count > 0)
            throw new Exception("Duplicate AudioEventId numeric values:\n- " + string.Join("\n- ", dupValue));
    }

    private static string BuildEnumFile(List<Record> records)
    {
        var sb = new StringBuilder(4096);

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by AudioEventIdGenerator from an AudioDatabase asset.");
        sb.AppendLine("// DO NOT EDIT MANUALLY. Edit AudioDatabase_Main and regenerate.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("public enum AudioEventId");
        sb.AppendLine("{");

        string[] groupOrder = new[] { "SFX", "UI", "AMBIENT", "VGM" };

        foreach (var group in groupOrder)
        {
            var groupRecords = records.Where(r => r.group == group).OrderBy(r => r.value).ToList();
            if (groupRecords.Count == 0) continue;

            sb.AppendLine($"    // {group}");
            foreach (var r in groupRecords)
            {
                if (r.deprecated)
                    sb.AppendLine("    [System.Obsolete(\"Deprecated audio event (kept for serialized stability).\", false)]");

                sb.AppendLine($"    {r.name} = {r.value},");
            }
            sb.AppendLine();
        }

        // unexpected groups
        var remainingGroups = records.Select(r => r.group).Distinct().Where(g => !groupOrder.Contains(g)).ToList();
        foreach (var group in remainingGroups)
        {
            var groupRecords = records.Where(r => r.group == group).OrderBy(r => r.value).ToList();
            if (groupRecords.Count == 0) continue;

            sb.AppendLine($"    // {group}");
            foreach (var r in groupRecords)
            {
                if (r.deprecated)
                    sb.AppendLine("    [System.Obsolete(\"Deprecated audio event (kept for serialized stability).\", false)]");

                sb.AppendLine($"    {r.name} = {r.value},");
            }
            sb.AppendLine();
        }

        sb.AppendLine("}");
        sb.AppendLine();

        return sb.ToString();
    }

    public static string SanitizeToIdentifier(string raw)
    {
        if (string.IsNullOrWhiteSpace(raw))
            return "Unnamed";

        raw = raw.Trim();

        var sb = new StringBuilder(raw.Length);
        bool prevUnderscore = false;

        for (int i = 0; i < raw.Length; i++)
        {
            char c = raw[i];

            if (char.IsLetterOrDigit(c) || c == '_')
            {
                sb.Append(c);
                prevUnderscore = false;
                continue;
            }

            if (char.IsWhiteSpace(c) || c == '-' || c == '/' || c == '\\' || c == '.')
            {
                if (!prevUnderscore && sb.Length > 0)
                {
                    sb.Append('_');
                    prevUnderscore = true;
                }
                continue;
            }
        }

        string result = sb.ToString().Trim('_');
        if (string.IsNullOrEmpty(result))
            result = "Unnamed";

        if (char.IsDigit(result[0]))
            result = "_" + result;

        return result;
    }
}
#endif